SELECT * FROM EMPLOYEES 
		WHERE EMPLOYEE_ID BETWEEN 100 AND 105;

SELECT * FROM EMPLOYEES 
		WHERE EMPLOYEE_ID IN(151 , 152, 153, 154 , 155);


SELECT * FROM EMPLOYEES 
        WHERE FIRST_NAME LIKE 'P%' OR FIRST_NAME LIKE 'p%'; 

SELECT * FROM EMPLOYEES 
        WHERE LAST_NAME LIKE '%A' OR LAST_NAME LIKE '%a'; 


SELECT * FROM EMPLOYEES 
        WHERE FIRST_NAME LIKE '%a%' OR FIRST_NAME LIKE '%A%';

SELECT * FROM EMPLOYEES 
        WHERE FIRST_NAME LIKE '__e%' OR FIRST_NAME LIKE '__E%';

SELECT * FROM EMPLOYEES 
        WHERE MANAGER_ID IS NULL;

SELECT * FROM EMPLOYEES 
        WHERE MANAGER_ID IS NOT  NULL;


INSERT INTO EMPLOYEES (EMPLOYEE_ID , FIRST_NAME , LAST_NAME , SALARY , DEPARTMENT_ID , EMAIL, HIRE_DATE, JOB_ID)
VALUES (207 , 'Ahmed', 'Mohamed' , 5000 ,100 , 'ahmdms', sysdate , 'SH_CLERK' );

SELECT * FROM EMPLOYEES
		WHERE JOB_ID = 'AD_VP' OR JOB_ID = 'IT_PROG';

SELECT * FROM EMPLOYEES ORDER BY LAST_NAME;
SELECT * FROM EMPLOYEES ORDER BY hire_date desc;
SELECT * FROM EMPLOYEES ORDER BY DEPARTMENT_ID , SALARY DESC;

SELECT  EMPLOYEE_ID ,FIRST_NAME, lower ( LAST_NAME)   FROM EMPLOYEES;

SELECT  EMPLOYEE_ID ,upper (FIRST_NAME) , LAST_NAME  FROM EMPLOYEES;



SELECT * FROM EMPLOYEES
		WHERE lower(LAST_NAME) = 'smith';




